[package]
name = "hexfoo_lib"

authors = ["Rich Churcher <rich.churcher@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[dependencies]
bevy = { features = ["dynamic_linking"], version = "0.12.0" }
